name: flutter_event_system
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # Updated to support latest package versions

dependencies:
  flutter:
    sdk: flutter
  
  # Core packages for functionality, updated to latest versions
  camera: ^0.11.2
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^12.0.1 # This was likely already up-to-date
  
  # State management, updated to latest major versions
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  
  # Utility packages, updated
  image: ^4.1.7
  path_provider: ^2.1.3
  csv: ^6.0.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linter, updated to latest major version
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/csv/students.csv